Update swift.yml

diff --git a/.github/workflows/swift.yml b/.github/workflows/swift.yml
--- a/.github/workflows/swift.yml
+++ b/.github/workflows/swift.yml
@@ -1,6 +1,3 @@
-# This workflow will build a Swift project
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
-
 name: Swift
 
 on:
@@ -11,7 +8,6 @@ on:
 
 jobs:
   build:
-
     runs-on: macos-latest
 
     steps:
@@ -20,3 +16,9 @@ jobs:
       run: swift build -v
     - name: Run tests
       run: swift test -v
+    - name: Post Job Cleanup
+      run: |
+        echo "Running cleanup"
+        git config --global --add safe.directory /Users/runner/work/WellNest/WellNest || :
+        git config --local --unset-all http.https://github.com/.extraheader || :
+      if: always() # Run this step even if previous steps failed
